version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie_library_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app